[toolchain]
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
whoplays = "2Vqzw8dQcNcdATQWSDtX8VNhCGeo45NscYX85pnCba2P"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
